version: 1.0.{build}
image: Visual Studio 2022

before_build:
  - cmd: nuget restore Pisces.sln

configuration: Debug
platform: Any CPU 

build:
  project: Pisces.sln
  verbosity: minimal
  
test:
  assemblies:
    ## Test the libraries
    - Core\$(OutDir)\Reclamation.Core.dll
    - TimeSeries\$(OutDir)\Reclamation.TimeSeries.dll

  categories:
    except:
      - DatabaseServer
      - Internal