//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd", IsNullable=false)]
public partial class TimeSeriesDatabaseDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PiscesInfo", typeof(TimeSeriesDatabaseDataSetPiscesInfo))]
    [System.Xml.Serialization.XmlElementAttribute("RatingTable", typeof(TimeSeriesDatabaseDataSetRatingTable))]
    [System.Xml.Serialization.XmlElementAttribute("Scenario", typeof(TimeSeriesDatabaseDataSetScenario))]
    [System.Xml.Serialization.XmlElementAttribute("SeriesCatalog", typeof(TimeSeriesDatabaseDataSetSeriesCatalog))]
    [System.Xml.Serialization.XmlElementAttribute("alarm", typeof(TimeSeriesDatabaseDataSetAlarm))]
    [System.Xml.Serialization.XmlElementAttribute("parametercatalog", typeof(TimeSeriesDatabaseDataSetParametercatalog))]
    [System.Xml.Serialization.XmlElementAttribute("quality_limit", typeof(TimeSeriesDatabaseDataSetQuality_limit))]
    [System.Xml.Serialization.XmlElementAttribute("seriesproperties", typeof(TimeSeriesDatabaseDataSetSeriesproperties))]
    [System.Xml.Serialization.XmlElementAttribute("sitecatalog", typeof(TimeSeriesDatabaseDataSetSitecatalog))]
    [System.Xml.Serialization.XmlElementAttribute("siteproperties", typeof(TimeSeriesDatabaseDataSetSiteproperties))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetPiscesInfo {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetRatingTable {
    
    private double xField;
    
    private double yField;
    
    private bool yFieldSpecified;
    
    /// <remarks/>
    public double x {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public double y {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ySpecified {
        get {
            return this.yFieldSpecified;
        }
        set {
            this.yFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetScenario {
    
    private int sortOrderField;
    
    private string nameField;
    
    private bool checkedField;
    
    private string pathField;
    
    private double sortMetricField;
    
    public TimeSeriesDatabaseDataSetScenario() {
        this.nameField = "";
        this.checkedField = false;
        this.pathField = "";
        this.sortMetricField = 0D;
    }
    
    /// <remarks/>
    public int SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public bool Checked {
        get {
            return this.checkedField;
        }
        set {
            this.checkedField = value;
        }
    }
    
    /// <remarks/>
    public string Path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double SortMetric {
        get {
            return this.sortMetricField;
        }
        set {
            this.sortMetricField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetSeriesCatalog {
    
    private int idField;
    
    private int parentIDField;
    
    private short isFolderField;
    
    private int sortOrderField;
    
    private string iconnameField;
    
    private string nameField;
    
    private string siteidField;
    
    private string unitsField;
    
    private string timeIntervalField;
    
    private string parameterField;
    
    private string tableNameField;
    
    private string providerField;
    
    private string connectionStringField;
    
    private string expressionField;
    
    private string notesField;
    
    private short enabledField;
    
    public TimeSeriesDatabaseDataSetSeriesCatalog() {
        this.parentIDField = 0;
        this.isFolderField = ((short)(0));
        this.sortOrderField = 1;
        this.iconnameField = "";
        this.nameField = "untitled";
        this.siteidField = "";
        this.unitsField = "";
        this.timeIntervalField = "";
        this.parameterField = "";
        this.tableNameField = "";
        this.providerField = "Series";
        this.connectionStringField = "";
        this.expressionField = "";
        this.notesField = "";
        this.enabledField = ((short)(0));
    }
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int ParentID {
        get {
            return this.parentIDField;
        }
        set {
            this.parentIDField = value;
        }
    }
    
    /// <remarks/>
    public short IsFolder {
        get {
            return this.isFolderField;
        }
        set {
            this.isFolderField = value;
        }
    }
    
    /// <remarks/>
    public int SortOrder {
        get {
            return this.sortOrderField;
        }
        set {
            this.sortOrderField = value;
        }
    }
    
    /// <remarks/>
    public string iconname {
        get {
            return this.iconnameField;
        }
        set {
            this.iconnameField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string siteid {
        get {
            return this.siteidField;
        }
        set {
            this.siteidField = value;
        }
    }
    
    /// <remarks/>
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public string TimeInterval {
        get {
            return this.timeIntervalField;
        }
        set {
            this.timeIntervalField = value;
        }
    }
    
    /// <remarks/>
    public string Parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
    
    /// <remarks/>
    public string TableName {
        get {
            return this.tableNameField;
        }
        set {
            this.tableNameField = value;
        }
    }
    
    /// <remarks/>
    public string Provider {
        get {
            return this.providerField;
        }
        set {
            this.providerField = value;
        }
    }
    
    /// <remarks/>
    public string ConnectionString {
        get {
            return this.connectionStringField;
        }
        set {
            this.connectionStringField = value;
        }
    }
    
    /// <remarks/>
    public string Expression {
        get {
            return this.expressionField;
        }
        set {
            this.expressionField = value;
        }
    }
    
    /// <remarks/>
    public string Notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    public short enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetAlarm {
    
    private string tablemaskField;
    
    private double highField;
    
    private bool highFieldSpecified;
    
    private double lowField;
    
    private bool lowFieldSpecified;
    
    private double deltaField;
    
    private bool deltaFieldSpecified;
    
    /// <remarks/>
    public string tablemask {
        get {
            return this.tablemaskField;
        }
        set {
            this.tablemaskField = value;
        }
    }
    
    /// <remarks/>
    public double high {
        get {
            return this.highField;
        }
        set {
            this.highField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool highSpecified {
        get {
            return this.highFieldSpecified;
        }
        set {
            this.highFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double low {
        get {
            return this.lowField;
        }
        set {
            this.lowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lowSpecified {
        get {
            return this.lowFieldSpecified;
        }
        set {
            this.lowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double delta {
        get {
            return this.deltaField;
        }
        set {
            this.deltaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deltaSpecified {
        get {
            return this.deltaFieldSpecified;
        }
        set {
            this.deltaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetParametercatalog {
    
    private string idField;
    
    private string timeintervalField;
    
    private string unitsField;
    
    private string statisticField;
    
    private string nameField;
    
    public TimeSeriesDatabaseDataSetParametercatalog() {
        this.timeintervalField = "Irregular";
        this.unitsField = " ";
        this.statisticField = "Inst";
        this.nameField = "";
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string timeinterval {
        get {
            return this.timeintervalField;
        }
        set {
            this.timeintervalField = value;
        }
    }
    
    /// <remarks/>
    public string units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public string statistic {
        get {
            return this.statisticField;
        }
        set {
            this.statisticField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetQuality_limit {
    
    private string tablemaskField;
    
    private double highField;
    
    private bool highFieldSpecified;
    
    private double lowField;
    
    private bool lowFieldSpecified;
    
    private double deltaField;
    
    private bool deltaFieldSpecified;
    
    /// <remarks/>
    public string tablemask {
        get {
            return this.tablemaskField;
        }
        set {
            this.tablemaskField = value;
        }
    }
    
    /// <remarks/>
    public double high {
        get {
            return this.highField;
        }
        set {
            this.highField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool highSpecified {
        get {
            return this.highFieldSpecified;
        }
        set {
            this.highFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double low {
        get {
            return this.lowField;
        }
        set {
            this.lowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lowSpecified {
        get {
            return this.lowFieldSpecified;
        }
        set {
            this.lowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double delta {
        get {
            return this.deltaField;
        }
        set {
            this.deltaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deltaSpecified {
        get {
            return this.deltaFieldSpecified;
        }
        set {
            this.deltaFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetSeriesproperties {
    
    private int idField;
    
    private int seriesidField;
    
    private string nameField;
    
    private string valueField;
    
    public TimeSeriesDatabaseDataSetSeriesproperties() {
        this.nameField = "";
        this.valueField = "";
    }
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public int seriesid {
        get {
            return this.seriesidField;
        }
        set {
            this.seriesidField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("")]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetSitecatalog {
    
    private string siteidField;
    
    private string descriptionField;
    
    private string stateField;
    
    private double latitudeField;
    
    private bool latitudeFieldSpecified;
    
    private double longitudeField;
    
    private bool longitudeFieldSpecified;
    
    private string elevationField;
    
    private string timezoneField;
    
    private string installField;
    
    private string horizontal_datumField;
    
    private string vertical_datumField;
    
    private double vertical_accuracyField;
    
    private bool vertical_accuracyFieldSpecified;
    
    private string elevation_methodField;
    
    private string tz_offsetField;
    
    private string active_flagField;
    
    private string typeField;
    
    private string responsibilityField;
    
    private string agency_regionField;
    
    public TimeSeriesDatabaseDataSetSitecatalog() {
        this.timezoneField = "";
    }
    
    /// <remarks/>
    public string siteid {
        get {
            return this.siteidField;
        }
        set {
            this.siteidField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public double latitude {
        get {
            return this.latitudeField;
        }
        set {
            this.latitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool latitudeSpecified {
        get {
            return this.latitudeFieldSpecified;
        }
        set {
            this.latitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double longitude {
        get {
            return this.longitudeField;
        }
        set {
            this.longitudeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool longitudeSpecified {
        get {
            return this.longitudeFieldSpecified;
        }
        set {
            this.longitudeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string elevation {
        get {
            return this.elevationField;
        }
        set {
            this.elevationField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("")]
    public string timezone {
        get {
            return this.timezoneField;
        }
        set {
            this.timezoneField = value;
        }
    }
    
    /// <remarks/>
    public string install {
        get {
            return this.installField;
        }
        set {
            this.installField = value;
        }
    }
    
    /// <remarks/>
    public string horizontal_datum {
        get {
            return this.horizontal_datumField;
        }
        set {
            this.horizontal_datumField = value;
        }
    }
    
    /// <remarks/>
    public string vertical_datum {
        get {
            return this.vertical_datumField;
        }
        set {
            this.vertical_datumField = value;
        }
    }
    
    /// <remarks/>
    public double vertical_accuracy {
        get {
            return this.vertical_accuracyField;
        }
        set {
            this.vertical_accuracyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vertical_accuracySpecified {
        get {
            return this.vertical_accuracyFieldSpecified;
        }
        set {
            this.vertical_accuracyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string elevation_method {
        get {
            return this.elevation_methodField;
        }
        set {
            this.elevation_methodField = value;
        }
    }
    
    /// <remarks/>
    public string tz_offset {
        get {
            return this.tz_offsetField;
        }
        set {
            this.tz_offsetField = value;
        }
    }
    
    /// <remarks/>
    public string active_flag {
        get {
            return this.active_flagField;
        }
        set {
            this.active_flagField = value;
        }
    }
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string responsibility {
        get {
            return this.responsibilityField;
        }
        set {
            this.responsibilityField = value;
        }
    }
    
    /// <remarks/>
    public string agency_region {
        get {
            return this.agency_regionField;
        }
        set {
            this.agency_regionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/TimeSeriesDatabaseDataSet.xsd")]
public partial class TimeSeriesDatabaseDataSetSiteproperties {
    
    private int idField;
    
    private string siteidField;
    
    private string nameField;
    
    private string valueField;
    
    public TimeSeriesDatabaseDataSetSiteproperties() {
        this.nameField = "";
        this.valueField = "";
    }
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string siteid {
        get {
            return this.siteidField;
        }
        set {
            this.siteidField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("")]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
